### Get all compounds
GET http://localhost:3000/compounds


### Get compound by id
GET http://localhost:3000/compounds/134


### Get compound by searching with trivial name
GET http://localhost:3000/compounds/search?trivialname=cho


### Create compound
POST http://localhost:3000/compounds
Content-Type: application/json

{
    "trivial_name": "test",
    "cas_number": "aksdhiuw",
    "inci_name": "ashdiuw",
    "smiles": "asdboqwy",
    "comedogenicity_class": 1
}


### Delete Compound
DELETE http://localhost:3000/compounds/239


### Update Compound
PATCH http://localhost:3000/compounds/239
Content-Type: application/json

{
    "comedogenicity_class": 2
}